### ISSUE TITLE
Multiple faces on game screen

### ISSUE THREAD

**Issue by aamarichal** [eecs394-spr15/IckyPicky#10]

**Comment by aamarichal** [comment]
Working on  putting paths to faces in an array and preloading all of them. Currently we've hit a bug here.

**Comment by jondavidford** [comment]
we load one more face with this commit dbbddfeaf52f3f1d579fc4b266436881902b9eba

**Comment by jondavidford** [comment]
this might be the commit for more faces c4305dfa8618bbfe7349ac1db05de
