### ISSUE TITLE
"Exciting thing" happens when you pick the nose

### ISSUE THREAD

**Issue by aamarichal** [eecs394-spr15/IckyPicky#13]

**Comment by arisatoyosaki** [comment]
do you guys want me to make a new finger icon, one from the front and one from the back, so when nose picking event occurs, we can flip back and forth from the front and back image so it looks like the finger is turning in the nose?

**Comment by arisatoyosaki** [comment]
when success, finger moves around. when lose, snot bubble enlargens, and after losing, green splat saying game over in an image

**Comment by arisatoyosaki** [comment]
Closed this due to descriptions on the sub-tasks added separately
