### ISSUE TITLE
add game instructions

### ISSUE THREAD

**Issue by jondavidford** [eecs394-spr15/IckyPicky#24]

**Comment by jondavidford** [comment]
maybe a brief tutorial?

**Comment by jondavidford** [comment]
here's an idea: on the homescreen there is a button that says "how to play" or something along those lines. Then it takes the user to a series of pictures that explain how to play the game. or maybe an interactive tutorial

**Comment by arisatoyosaki** [comment]
i think you could add a question mark icon to the homescreen for that

**Comment by pweldon93** [comment]
OFFICIAL DESCRIPTION: Only have instructions on first game. 
- " Tap here" over the nose
- "Try to pick the nose" in top of screen

**Comment by arisatoyosaki** [comment]
for now alex will add a two line js notification when user opens the game. when arisa and jon finishes setting up the back end, we will try to store user "first play" information.

**Comment by aamarichal** [comment]
Tutorial added! And it's not even a js notification!

**Comment by aamarichal** [comment]
Also: user tracking shouldn't be necessary. The tutorial is very non-invasive and should be okay to have up every new game.
